### ISSUE TITLE
Show results in export

### ISSUE THREAD

**Issue by gesslinger** [jorupp/ExportTestCases#10]
Currently the results are not exported, although there are reserved fields in the excel sheet (Actual Result, Pass/Fail).
Is this feature not implemented yet, or are there any issues to get this information from TFS?

**Comment by jorupp** [comment]
The goal of the tool was to generate a spreadsheet the user could fill out to execute a test, not export the result of a test run - sorry if the description was confusing.

You might be able to modify it to export the result of a run.  In that case, you'd want to start from the result of a test (not sure where in the API that is) and go from there, rather than from the ITestSuiteBase that TestCaseExport/Exporter.cs uses.
